/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function extractImagesPerPage(buffer: Buffer): Array<PageImage>

export declare function extractTextPerPage(buffer: Buffer): Array<PageText>

export interface PageImage {
  page: number
  imageIndex: number
  width: number
  height: number
  data: Buffer
  colorSpace: string
  bitsPerComponent: number
  filter: string
}

export interface PageText {
  page: number
  text: string
}

export interface PdfMeta {
  pageCount: number
  version: string
  isLinearized: boolean
}

export declare function pdfMetadata(buffer: Buffer): PdfMeta

export declare function plus100(input: number): number
