/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PdfDown {
  constructor(buffer: Buffer)
  /** Sync: extract text per page (reuses the already-parsed document) */
  textPerPage(): Array<PageText>
  /** Sync: extract images per page (reuses the already-parsed document) */
  imagesPerPage(): Array<PageImage>
  /** Sync: get PDF metadata (reuses the already-parsed document) */
  metadata(): PdfMeta
  /** Async: extract text per page on the libuv thread pool */
  textPerPageAsync(): Promise<Array<PageText>>
  /** Async: extract images per page on the libuv thread pool */
  imagesPerPageAsync(): Promise<Array<PageImage>>
  /** Async: get PDF metadata on the libuv thread pool */
  metadataAsync(): Promise<PdfMeta>
}

export declare function extractImagesPerPage(buffer: Buffer): Array<PageImage>

export declare function extractImagesPerPageAsync(buffer: Buffer): Promise<Array<PageImage>>

export declare function extractTextPerPage(buffer: Buffer): Array<PageText>

export declare function extractTextPerPageAsync(buffer: Buffer): Promise<Array<PageText>>

export interface PageImage {
  page: number
  imageIndex: number
  width: number
  height: number
  data: Buffer
  colorSpace: string
  bitsPerComponent: number
  filter: string
  xobjectName: string
  objectId: string
}

export interface PageText {
  page: number
  text: string
}

export interface PdfMeta {
  pageCount: number
  version: string
  isLinearized: boolean
}

export declare function pdfMetadata(buffer: Buffer): PdfMeta

export declare function pdfMetadataAsync(buffer: Buffer): Promise<PdfMeta>
